### ISSUE TITLE
Add class/classList properties

### ISSUE THREAD

**Issue by philer** [Cweili/solid-fa#71]
Hey, great library! I love the simplicity.

One thing I'm missing, though, is the option to add custom classes to the root `<svg>` element. Something like

```jsx
<Fa icon={faTrash} class="hover-red" />
```
can be quite useful.

Either way, thanks :)

**Comment by Cweili** [comment]
Thanks @mrshmllow , [version 0.2.0](https://www.npmjs.com/package/solid-fa) published.
